[main]
    certname = puppet-server
    server = puppet-server
    environment = production
    runinterval = 30m
    strict_variables = true

[master]
    vardir = /opt/puppetlabs/server/data/puppetserver
    logdir = /var/log/puppetlabs/puppetserver
    rundir = /var/run/puppetlabs/puppetserver
    pidfile = /var/run/puppetlabs/puppetserver/puppetserver.pid
    codedir = /etc/puppetlabs/code
    autosign = /etc/puppetlabs/puppet/autosign.conf
    dns_alt_names = puppet,puppet-server,localhost
